import React, { useEffect, useState } from 'react';
import type { Product } from '../../types';

export const EditProductModal: React.FC<{ product:Product|null; onClose:()=>void; onSave:(id:string,data:Partial<Product>)=>void }> = ({product,onClose,onSave}) => {
  const [form,setForm]=useState({name:'',sku:'',category:'',unit:'un',minStock:0,maxStock:0,costPrice:0,salePrice:0,supplier:'',image:''});
  useEffect(()=>{if(product)setForm({name:product.name,sku:product.sku,category:product.category,unit:product.unit,minStock:product.minStock,maxStock:product.maxStock||0,costPrice:product.costPrice,salePrice:product.salePrice,supplier:product.supplier||'',image:product.image||''});},[product]);
  if(!product)return null;
  const set=(key:keyof typeof form,value:string|number)=>setForm(prev=>({...prev,[key]:value}));
  return <div className="fixed inset-0 z-50 bg-slate-900/40 flex items-center justify-center p-4"><form onSubmit={e=>{e.preventDefault();onSave(product.id,form);}} className="bg-white rounded-xl p-6 w-full max-w-xl space-y-4"><div className="flex justify-between"><h2 className="font-bold text-lg">Editar produto</h2><button type="button" onClick={onClose}>×</button></div><p className="text-xs text-slate-500">Ajustes de saldo devem ser feitos pela ação de ajuste para manter o histórico.</p><div className="grid grid-cols-2 gap-3">{(['name','sku','category','unit','supplier','image'] as const).map(k=><label key={k} className="text-xs">{({name:'Descrição',sku:'Código',category:'Categoria',unit:'Unidade',supplier:'Fornecedor',image:'URL da foto'} as any)[k]}<input required={k==='name'||k==='sku'} type="text" value={form[k]} onChange={e=>set(k,e.target.value)} className="mt-1 w-full border rounded-md px-3 py-2" /></label>)}{(['minStock','maxStock','costPrice','salePrice'] as const).map(k=><label key={k} className="text-xs">{({minStock:'Estoque mínimo',maxStock:'Estoque máximo',costPrice:'Preço de compra',salePrice:'Preço de venda'} as any)[k]}<input type="number" min="0" step="0.01" value={form[k]} onChange={e=>set(k,Number(e.target.value))} className="mt-1 w-full border rounded-md px-3 py-2" /></label>)}</div><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="px-4 py-2 border rounded-md">Cancelar</button><button className="px-4 py-2 bg-blue-700 text-white rounded-md">Salvar alterações</button></div></form></div>;
};
